HW5 on code review
Stanislav-R/Hillel_Lessons pull request #1
Opened 2021-05-29 16:56 UTC by Stanislav-R

HW4.py contains HW5 in the end

2021-05-29 17:33 UTC, dbradultest requested changes

2021-05-29 17:33 UTC, dbradultest commented on 1-5/HW4.py
> +    query = f"select i.Name, sum(ii.Milliseconds)/(1000*60) as duration from genres as i join tracks " \
оформите запрос в виде многострочной строки:
```
query = f"""
select
    i.name, sum(...) as duration, ...
from genres as g
...
"""
```

Это повысит читабельность кода.

2021-05-29 17:33 UTC, dbradultest commented on 1-5/HW4.py
> +    query = f"select tracks.Name, (count(*) * invoice_items.UnitPrice * invoice_items.Quantity) as profit " \
см. выше

2021-05-29 17:33 UTC, dbradultest commented on 1-5/HW4.py
> +    query = f"select tracks.Name, (count(*) * invoice_items.UnitPrice * invoice_items.Quantity) as profit " \
умножать на `count(*)` точно нужно?

2021-05-30 09:26 UTC, Stanislav-R commented
PR merged

2021-05-30 09:26 UTC, closed without merging